services:
  mysql:
    image: mysql:5.7
    container_name: fastapi_chatbot-mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/mysql.conf.d/custom.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fastapi
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - local_network

  mongo:
    image: mongo:latest
    container_name: fastapi_chatbot-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./.docker/mongo/data:/data/db
    ports:
      - "27017:27017"
    networks:
      - local_network

  qdrant:
    image: qdrant/qdrant:v1.2.0
    container_name: fastapi_chatbot-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./.docker/qdrant/data:/qdrant/storage
    networks:
      - local_network
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334

  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: fastapi_chatbot
    volumes:
      - ./:/app
    ports:
      - "9098:8000"
    networks:
      - local_network
    environment:
      DB_HOST: fastapi_chatbot-mysql
      MONGO_DB_HOST: fastapi_chatbot-mongodb

networks:
  local_network:
    driver: bridge
